= Mistral-7B Model Card

Mistral-7b-instruct-v01, developed by mistralai, is "a instruct fine-tuned version of the Mistral-7B-v0.1 generative text model using a variety of publicly available conversation datasets." This folder contains source code that adapts the model for running on RDU. 

Model Transformers Version: 4.35.0

== Architecture Changes 

Model Zoo models maintain checkpoint compatibility with Hugging Face, so there are no architecture differences. 

* See  xref:patch_mistral.py[] for details on how we've modified the model to run on RDU
* See xref:../../examples/training/README.adoc[the training README] and the  xref:../../examples/text_generation/README.adoc[text generation README] for discussions of CPU/RDU differences. 

== General Use Cases

See the link:https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.1[Mistral-7B-Instruct-v0.1 Model Card]. SambaNova does not ship checkpoints for this model. Instead, you can use the Model Zoo model source with the corresponding Hugging Face checkpoint. 

== Data Preparation

Our models expect data in HDF5 format. See the SambaNova data preparation scripts in link:https://github.com/sambanova/generative_data_prep[this public GitHub repo]. 

== Model Parameters and Configuration

See link:https://docs-staging.sambanova.ai/developer/latest/modelzoo-best-practices.htm[Model Zoo Best Practices] for a discussion of modification options and limitations.  

== Supported Models
Model Zoo currently supports the following Mistral versions: 

* Mistral-7B-v0.1


link:https://docs-staging.sambanova.ai/developer/latest/modelzoo-best-practices.htm[Model Zoo Best Practices] lists the checkpoints that we have tested, but you can use other Hugging Face checkpoints for the corresponding model. 

