= Mistral-7B model card

Mistral-7b-instruct-v01, developed by mistralai, is "a instruct fine-tuned version of the Mistral-7B-v0.1 generative text model using a variety of publicly available conversation datasets." This folder contains source code that adapts the model for running on RDU. 

Model Transformers Version: 4.35.0

== Architecture changes 

Model Zoo models maintain checkpoint compatibility with Hugging Face, so there are no architecture differences. 

* See  xref:patch_mistral.py[] for details on how we've modified the model to run on RDU
* See xref:../../examples/training/README.adoc[the training README] and the  xref:../../examples/text_generation/README.adoc[text generation README] for discussions of CPU/RDU differences. 

== General use cases

See the link:https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.1[Mistral-7B-Instruct-v0.1 Model Card]. SambaNova does not ship checkpoints for this model. Instead, you can use the Model Zoo model source with the corresponding Hugging Face checkpoint. 

== Data preparation

Our models expect data in HDF5 format. See the SambaNova data preparation scripts in link:https://github.com/sambanova/generative_data_prep[this public GitHub repo]. 

== Model parameters and configuration

See link:https://docs.sambanova.ai/developer/latest/modelzoo-best-practices.html[Model Zoo Best Practices] for a discussion of modification options and limitations.  

== Supported models
Model Zoo currently supports the following Mistral versions: 

* Mistral-7B-v0.1


link:https://docs.sambanova.ai/developer/latest/modelzoo-best-practices.html[Model Zoo Best Practices] lists the checkpoints that we have tested, but you can use other Hugging Face checkpoints for the corresponding model. 

== Data parallel functionality

Data-parallelism is a method where the dataset is split into several parts, and each part is processed at the same time by different replicas of the application.

The following Mistral models support 16-way data parallel functionality:

* Mistral-7b

NOTE: The 16-way Data Parallel (DP) enablement feature works fine with 4K sequence lengths. However, it has a risk of running out of memory for 8K and higher sequence lengths.

See xref:developer::data-parallel.adoc#_what_is_data_parallel[What is data parallel] for more information.